config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"

  resources :groups do
    member do
      get 'add', to: 'groups#add'
      post 'add', to: 'groups#update_group'
      post 'exit', to: 'groups#exit'
      resources :messages
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
    validates :group_name, :group_owner, presence: true
    validates :group_name, uniqueness: true
    has_many :group_user_infos
end

app/models/group_user_info.rb
class GroupUserInfo < ApplicationRecord
    validates :group_name, :user_id, presence: true
    after_create_commit do
        user = User.find_by(id: self.user_id)
        broadcast_append_to user, target: "groups"
        # broadcast_append_to group, target: "participants", partial: "group_user_infos/participant"
    end
    belongs_to :user, primary_key: :id, foreign_key: :user_id
    belongs_to :group, primary_key: :group_name, foreign_key: :group_name
end

app/models/message.rb
class Message < ApplicationRecord
    validates :body, :group_id, :user_id, presence: true
    after_create_commit do
        group = Group.find_by(id: self.group_id)
        broadcast_append_to group, target: "messages"
    end
    belongs_to :user, primary_key: :id, foreign_key: :user_id
    belongs_to :group, primary_key: :id, foreign_key: :group_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :group_user_infos
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :authenticate_user!
    def index
        @groups = GroupUserInfo.where(user_id: current_user.id)
    end

    def new
    end

    def show
        params.permit(:id)
        @group_to_be_shown = Group.find_by(id: params[:id])
        @messages = Message.where(group_id: params[:id])
        @group_user_infos = GroupUserInfo.where(group_name: @group_to_be_shown.group_name)
    end

    def create
        params.permit(:group_name)
        @group = Group.new(group_name: params[:group_name],group_owner: current_user.id)
        @group.save
        @group_user_info = GroupUserInfo.new(group_name: params[:group_name], user_id: current_user.id, group_owner: @group.group_owner)
        @group_user_info.save
    end

    def destroy
        params.permit(:id)
        @group = Group.find_by(id: params[:id])
        GroupUserInfo.where(group_name: @group.group_name).each do |elem|
            elem.destroy
        end
        Message.where(group_id: @group.id).each do |elem|
            elem.destroy
        end
        @group.destroy
        redirect_to groups_path
    end

    def add
        params.permit(:id)
        @group = Group.find_by(id: params[:id])
    end

    def update_group
        params.permit(:user,:id)
        @group_user_info = GroupUserInfo.new(
            group_name: Group.find_by(id: params[:id]).group_name,
            user_id: User.find_by(email: params[:user]).id,
            group_owner: Group.find_by(id: params[:id]).group_owner
        )
        @group_user_info.save
    end

    def exit
        params.permit(:id)
        @message = Message.new(body: "Left the group", group_id:params[:id],user_id: current_user.id)
        @message.save
        @group_user_info = GroupUserInfo.where(group_name: Group.find_by(id: params[:id]).group_name).find_by(user_id: current_user.id)
        @group_user_info.destroy
        redirect_to groups_path
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!

    def new
    end

    def create
        params.permit(:body,:id)
        @message = Message.new(
            body: params[:body],
            group_id: params[:id],
            user_id: current_user.id
        )
        @message.save
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/group_user_infos/_group_user_info.html.erb
<%group = Group.find_by(group_name: group_user_info.group_name)%>
<%show_add = (group_user_info.user_id.to_i == group_user_info.group_owner.to_i)%>
<div style="padding:4px;">
    <div style="display:flex;flex-direction:column;align-items:center;justify-content:space-between;width: 30rem;height:auto;background-color:#1B1A55;border-radius:40px;color:white;padding:5px;box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);">
        <div><%= group.group_name%></div>
        <div style="padding:10px;">
            <%= button_to "Owner: #{User.find_by(id:group.group_owner).email}", "#", class: "btn btn-outline-light btn-submit" %>
        </div>
        <div style="display:flex;align-items:center;justify-content:space-around;width:15rem;padding:10px;">
            <%if show_add%>
                <%= button_to "Delete", group_path(group), method: :delete, class: "btn btn-outline-danger btn-submit" %>
                <%= button_to "Add", add_group_path(group), method: :get, class: "btn btn-outline-warning btn-submit" %>
            <%else%>
                <%=button_to "Exit", exit_group_path(group), class: "btn btn-outline-primary btn-submit" %>
            <%end%>
            <%= button_to "View", group_path(group), method: :get, class: "btn btn-outline-info btn-submit" %>
        </div>
    </div>
</div>

app/views/group_user_infos/_participant.html.erb
<%user = User.find_by(id: group_user_info.user_id)%>
<div><%=user.email%></div>

app/views/groups/_group.html.erb
<div style="padding:4px;">
    <div style="display:flex;flex-direction:column;align-items:center;justify-content:space-between;width: 30rem;height:auto;background-color:#1B1A55;border-radius:40px;color:white;padding:5px;box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);">
        <div><%= group.group_name %></div>
        <div style="display:flex;align-items:center;justify-content:space-around;width:15rem;padding:10px;">
            <%= button_to "view", group_path(group), method: :get, class: "btn btn-outline-info btn-submit" %>
            <%= button_to "delete", group_path(group), method: :delete, class: "btn btn-outline-danger btn-submit" %>
            <%= button_to "add", add_group_path(group), method: :get, class: "btn btn-outline-warning btn-submit" %>
        </div>
    </div>
</div>

app/views/groups/add.html.erb
<div style="display:flex;height:100vh;background-color:#435055;flex-direction:column;align-items:center;justify-content:center;">
    <div style="background-color:#535C91;border-radius:20px;font-weight:bold;color:white;box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);padding:20px;">
    <%= form_with url: add_group_path, method: :post, class: "d-flex", role: "search", style: "padding:10px;"%>
        <%= text_field_tag :user, nil, placeholder: "Add user", class: "form-control me-2"%>
        <div style="padding:0px 10px;"><%= submit_tag "Add", class: "btn btn-warning" %></div>
        <%= link_to "Close", groups_path , class:"btn btn-primary" %>
    </div>
</div>

app/views/groups/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@group) %>

app/views/groups/index.html.erb
<div style="background-color:#435055;height:100vh;display:flex; justify-content:center;">
    <div style="padding:10px;display:flex;flex-direction:column;align-items:center;justify-content:flex-start;border-radius: 50px;overflow-y:auto;">
        <div style="padding:10px 40px;display:block;">
            <%= form_with url: groups_path, method: :post, class: "d-flex", role: "search", style: "padding:10px;"%>
            <%= text_field_tag :group_name,nil ,placeholder: "Add new group", class: "form-control me-2"%>
            <%= submit_tag "Create", class: "btn btn-success" %>
        </div>
        <div style="display:flex;flex-direction:column;overflow-y:auto;">
            <%= turbo_stream_from current_user%>
                <div id="groups">
                    <%= render @groups %>
                </div>
        </div>
    </div>
</div>

app/views/groups/show.html.erb
<%group = Group.find_by(id: params[:id])%>
<div style="background-color:#435055;height:100vh;display:flex;flex-direction:column;align-items:center;">
    <div style="padding:3px;">
    <%=link_to " <- Back to groups", groups_path, class: "btn btn-secondary"%>
    <button onclick="location.reload()" class="btn btn-primary">Start Chatting Click here</button>
    </div>
    <div style="display:flex;">
        <div style="background-color:black;width:55rem;height:45rem;display:grid;grid-template-rows:1fr 10fr 1fr;color:white;border-radius: 50px;box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);margin-right:20px;">
            <div style="display:flex;align-items:center;justify-content:space-around;background-color:#2C3333;border-radius:50px 50px 0px 0px;">
                <div><h2><%=group.group_name%></h2></div>
            </div>
            <div style="display:flex;overflow-y:auto;">
            <%=turbo_stream_from group%>
                <div id="messages">
                    <%= render @messages%>
                </div>
            </div>
            <div style="background-color:white;padding:10px 40px;margin-top:4px;display:block;border-radius:0px 0px 50px 50px">
                <%= form_with url: messages_path, method: :post, class: "d-flex", role: "search", style: "padding:10px;"%>
                <%= text_field_tag :body,nil ,placeholder: "Message...", class: "form-control me-2"%>
                <%= submit_tag "Send", class: "btn btn-success" %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Group Chat Room" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
    <% if current_user%>
    <%=".message#{current_user.id}"%>{
      align-items:flex-end !important;
    }
    <%=".message#{current_user.id}"%> > * {
      background-color:#F4A261 !important;
    }
    <%end%>
    </style>

  </head>

  <body>
    <nav class="navbar bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand">Groups</a>
        <% if current_user%>
        <%= button_to "Logout #{current_user.email}", destroy_user_session_path, method: :delete, class:"btn btn-danger"%>
        <%else%>
        <%= link_to "Login", new_user_session_path , class:"btn btn-outline-primary"%>
        <%end%>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class=<%="message#{message.user_id}"%> style="display:flex;flex-direction:column;width:55rem;align-items:flex-start;">
    <div style="background-color:#CDFADB;color:black;width:300px;margin:5px 30px;font-size:1.25rem;padding:10px 30px;border-radius:50px;box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);">
        <div style="font-size:0.7rem;margin-right:200px"><%=User.find_by(id: message.user_id).email%></div>
            <%=message.body%>
    </div>
</div>

app/views/pages/home.html.erb
<div style="display:flex;flex-direction:column;align-items:center;justify-content:center;background-color:#435055;height:100vh;">
    <%if current_user%>
        <div>
        <%= link_to "Start Coversations", groups_path, class: "btn btn-success btn-lg"%>
        </div>
    <%else%>
        <div style="height:100vh;display:flex;align-items:center;justify-content:center;">
            <div style="padding:10px;">
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg"%>
            </div>
            <div style="padding:10px;">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
            </div>
        </div>
    <%end%>
</div>